export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';

export const INIT_PRODUCT = 'INIT_PRODUCT';
export const COLOR_ADDED = 'COLOR_ADDED';
export const NAME_ADDED = 'NAME_ADDED';
export const STICKER_ADDED = 'STICKER_ADDED';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAILED = 'LOAD_PRODUCTS_FAILED';